### PR TITLE
Updated for compatibility with v1.14 Geyser API

### PR DESCRIPTION
**Pull request by amilbourne**
This PR updates the plugin to work with the 1.14 version of the validator.  It should probably be in a new branch, but I can't create one (happy to resubmit a new PR if you want to create one).

The updates all centre on changes to the object model used by the Geyser plugin.  I have reflected these changes in the proto definition, which makes it somewhat incompatible with previous versions.

I hope this is a useful update.

### CODE REVIEW

**Comment by nyetwurk** [comment]
Yes, need to make a 1.14 branch or at least a real "main" which is constantly updated

**Comment by nyetwurk** [comment]
Please rebase against `Cargo.toml` and sign your commit.. will merge and also branch v1.15 when ready.

**Comment by nyetwurk** [comment]
@dependabot rebase

**Comment by amilbourne** [comment]
Rebased as requested.  Thanks for creating the branch.

**Comment by nyetwurk** [comment]
Done. Thank you!
I have created `main` instead of `v1.15` work as well.

**Pull request merged**
