### PR TITLE
Support v1.13 validators

### PR DESCRIPTION
**Pull request by amilbourne**
This is a small commit that contains the correct dependencies to run against the v1.13.6 validator (current main-net)
This PR is against main branch, but it should probably go into a v1.13 branch (could you create one as a branch from v1.10?)

It is based on the v1.10 branch because the object model in v1.13 seems to be the same as v1.10, and not the same as v1.11

### CODE REVIEW

**Comment by amilbourne** [comment]
@nyetwurk - Sorry, this PR looks like a bit of a mess because there is no v1.13 branch

**Comment by nyetwurk** [comment]
No worries, I'll get it straightened out.

**Comment by nyetwurk** [comment]
I have created a 1.13 branch

**Comment by nyetwurk** [comment]
Latest solana 1.13 is 1.13.7; I was about to update the 1.13 branch to that but I thought better of it as it would likely cause more conflicts with your branch.

**Comment by amilbourne** [comment]
@nyetwurk I used 1.13.6 rather than 1.13.7 because 1.13.6 is currently in use.  I think it should work with 1.13.7 but I haven't tested it so I stuck with 1.13.6

**Comment by amilbourne** [comment]
I also downgraded a couple of the dependencies because Rust 59 (which the 1.13 validator seems to build against) didn't like the newer versions.  That said, I may have got in a muddle and it may be possible to use the later versions against 59.  Again, I stuck with the downgrades because I tested that and know it works.

**Comment by nyetwurk** [comment]
Recreated based on v1.10

**Comment by amilbourne** [comment]
OK, I force pushed again and it looks right now.
I have stuck with the 1,13,6 validator version because that is what I tested and I don't have time to test again now.  1.13.7 should work, but I am playing safe.

**Comment by nyetwurk** [comment]
Ok, i have taken all I can from your branch, you can keep yours at 1.13.6 if you like.. not sure what to do with this MR?

**Comment by amilbourne** [comment]
This PR is a total mess :-)
As long as you have a working v1.13 branch then feel free to close this.
The changes were not that complex.

**Pull request closed without merging**
